[package]
name = "rust-rewrite"
version = "0.1.0"
edition = "2024"

[dependencies]
argparse = "0.2.2"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
glob = "0.3.4"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
shellexpand = "3.1.2"
yaml-rust = "0.4.5"
prettytable-rs = "0.10"
indexmap = { version = "2.14.0", features = ["serde"] }
notify = "8.2"
x11 = "2.21.0"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
lazy_static = "1.5.0"
x11rb = { version = "0.14.0", features = ["allow-unsafe-code"] }
